### ISSUE TITLE
Missing annotation files?

### ISSUE THREAD

**Issue by pauline-ng** [mebbert/Dark_and_Camouflaged_genes#2]
Hi Mark,

Thanks for making this, I'm really excited to try this out. 

I'm trying to use your supplied .bed files to run steps 6-10.  I think there are some files missing for steps 9 & 10. Can you upload the corresponding annotation files? 

Files seem to be missing:

**09_FIND_FALSE_POSITIVES /submit.sh**
`CAMO_ANNOTATION="../results/hg38_no_alt/illuminaRL100/illuminaRL100.hg38_no_alt.camo_annotations.txt"`

**10_VARIANT_FILTERING**
`ANNO_BED = "./results/annotations/hg38/Homo_sapiens.GRCh38.93.annotation.hg38.bed"`

Could you put the annotation files (that correspond to your bed files) in github? I'm using b37.

Thank you,
Pauline

**Comment by pauline-ng** [comment]
I ran steps 4 and 5 and generated the necessary files.

**Comment by rosaricla** [comment]
Hi @pauline-ng ,

I am facing the same problem as you when I try to run steps 6-10. After following your comments, I have seen that you got them by running step 4 and 5. However, I can't run step 5 because I can't find the following files:

`ILL100_LOW_COV="../results/illuminaRL100/combined/IlluminaRL100.hg19.combined.dark.low_depth.bed" #Combined ill100 depth output from step 2`
`ILL100_LOW_MAPQ="../results/illuminaRL100/combined/IlluminaRL100.hg19.combined.dark.mapq.bed" #Combined ill100 mapq output from step 2`

May I ask you where you got these three files from? Or you finally ran all steps 0-10?

Thank you in advance,
Rosa

**Comment by pauline-ng** [comment]
Hi @rosaricla ,

I got those files from the folder `dark_bed_files` .
If you're using b38, something like:

```
ILL100_LOWCOV="dark_bed_files/hg38/illuminaRL100.hg38_no_alt.low_depth-merged.bed"
ILL100_LOWMAPQ="dark_bed_files/hg38/illuminaRL100.hg38_no_alt.low_mapq-merged.bed"
```

Good luck!
Pauline

**Comment by mebbert** [comment]
Hello @rosaricla and @pauline-ng,

My apologies for not chiming in here before. We need to clarify on the main page that the first several steps do NOT need to be run if your goal is to rescue variants. The first several steps only need to be performed once per reference genome because those steps are to define the dark and camouflaged regions. We also provide those steps for transparency so others can validate or replicate our work, etc.

So, yes, @pauline-ng is correct that the bed files are already in place for you.

Please let us know if you don't see the bed files you need and we'll try to get you going.

**Comment by rosaricla** [comment]
Hello @mebbert and @pauline-ng ,

Thank you for your answers!

@mebbert It would be great if you could provide all the files needed to be able to run steps 6-10 without the previous steps 0 to 5. As Pauline said, two files are missing, one for step 9 and one for step 10.

The missing files are the followings:

```
09_FIND_FALSE_POSITIVES 
CAMO_ANNOTATION="../results/hg19_no_alt/illuminaRL100/illuminaRL100.hg19_no_alt.camo_annotations.txt"

10_VARIANT_FILTERING
ANNO_BED = "./results/annotations/hg19/Homo_sapiens.GRCh37.87.annotation.hg19.bed"
```

As @pauline-ng said, it is possible to obtain them by running the steps 4 and 5, howeverto execute these steps the [dark_bed_files](https://github.com/mebbert/Dark_and_Camouflaged_genes/tree/master/dark_bed_files) are required but these are not available in your resources for hg19 (the build I am working with) As they are not available, I would need to run through all the steps to get all the files needed for hg19.

Thanks again,
Rosa

**Comment by mebbert** [comment]
Thank you both for bringing this to our attention, and especially for your patience. We've been slowly transitioning our lab to a new institution (U. Kentucky), so we've been very distracted. We're slowly getting things going again, and should be more responsive going forward.

We're looking into this. I don't see any reason we would have left those files out, but we're double-checking.

We'll be in touch soon!

**Comment by mebbert** [comment]
Re-opening issue.

**Comment by KaitlynSparks** [comment]
Hi there,

Would it be possible to revisit this?

Thanks,
Kaitlyn
